image:
  name: "catenax-ng/product-core-managed-identity-wallets_service"
  tag: "0.3.2"
allowEmptyPassword: "\"yes\""
db:
  jdbcDriver: "org.postgresql.Driver"
namespace: "managed-identity-wallets"
logging:
  exposed: "INFO"
wallet:
  catenaXBpn: "BPNL000000000000"
acapy:
  imageName: "catenax-ng/product-core-managed-identity-wallets_acapy"
  tag: "0.7.4-rc1"
  ledgerUrl: "https://idu.cloudcompass.ca"
  label: "CatenaXIssuer"
  logLevel: "INFO"
  networkIdentifier: "idunion:test"
  databaseHost: "managed-identity-wallets-acapy-postgresql"
  secret:
    name: "catenax-managed-identity-wallets-acapy-secrets"
    path: "managed-identity-wallets/dev/catenax-managed-identity-wallets-acapy-secrets"
acapy-postgresql:
  enabled: true
  auth:
    existingSecret: "postgres-acapy-secret-config"
  secret:
    name: "postgres-acapy-secret-config"
    path: "managed-identity-wallets/dev/postgres-acapy-secret-config"
postgresql:
  enabled: false
  auth:
    existingSecret: "postgres-managed-identity-wallets-secret-config"
app:
  version: "0.10.0"
managed-identity-wallets:
  secret:
    name: "catenax-managed-identity-wallets-secrets"
    path: "managed-identity-wallets/dev/catenax-managed-identity-wallets-secrets"