auth:
  jwksUrl: "https://catenaxintakssrv.germanywestcentral.cloudapp.azure.com/iamcentralidp/auth/realms/CX-Central/protocol/openid-connect/certs"
  issuerUrl: "https://catenaxintakssrv.germanywestcentral.cloudapp.azure.com/iamcentralidp/auth/realms/CX-Central"
  redirectUrl: "https://managed-identity-wallets.int.demo.catena-x.net/callback"
  realm: "CX-Central"
  role: "access"
datapoolUrl: "https://catenax-bpdm-int.demo.catena-x.net"
acapy:
  logLevel: "INFO"
  endpointPort: "8000"
  endpointUrl: "https://managed-identity-wallets.int.demo.catena-x.net:8000/"
  adminPort: "11000"
  adminUrl: "http://localhost:11000"
certificate:
  host: "managed-identity-wallets.int.demo.catena-x.net"