auth:
  jwksUrl: "https://catenaxdev003akssrv.germanywestcentral.cloudapp.azure.com/iamcentralidp/auth/realms/CX-Central/protocol/openid-connect/certs"
  issuerUrl: "https://catenaxdev003akssrv.germanywestcentral.cloudapp.azure.com/iamcentralidp/auth/realms/CX-Central"
  redirectUrl: "https://custodian-dev.germanywestcentral.cloudapp.azure.com/callback"
  realm: "CX-Central"
  role: "access"
datapoolUrl: "https://catenax-bpdm-dev.germanywestcentral.cloudapp.azure.com"
image:
  registry: "ghcr.io"
  tag: "latest-develop"
acapy:
  logLevel: "DEBUG"
  ledgerUrl: "https://indy-test.bosch-digital.de/"
  endpointPort: "8000"
  endpointUrl: "https://managed-identity-wallets.dev.demo.catena-x.net:8000/"
  adminPort: "11000"
  adminUrl: "http://localhost:11000"
certificate:
  host: "managed-identity-wallets.dev.demo.catena-x.net"