---
apiVersion: v1
kind: Secret
metadata:
  annotations:
    avp.kubernetes.io/path: {{ .Values.acapy.secret.path }}
  name: {{ .Values.acapy.secret.name }}
  namespace: {{ .Release.Namespace }}
type: Opaque
---
apiVersion: v1
kind: Secret
metadata:
  annotations:
    avp.kubernetes.io/path: {{ .Values.acapyPostgresql.secret.path }}
  name: {{ .Values.acapyPostgresql.secret.name }}
  namespace: {{ .Release.Namespace }}
type: Opaque
---
apiVersion: v1
kind: Secret
metadata:
  annotations:
    avp.kubernetes.io/path: {{ .Values.managedIdentityWallets.secret.path }}
  name: {{ .Values.managedIdentityWallets.secret.name }}
  namespace: {{ .Release.Namespace }}
type: Opaque