# /********************************************************************************
# * Copyright (c) 2021,2023 Contributors to the Eclipse Foundation
# *
# * See the NOTICE file(s) distributed with this work for additional
# * information regarding copyright ownership.
# *
# * This program and the accompanying materials are made available under the
# * terms of the Apache License, Version 2.0 which is available at
# * https://www.apache.org/licenses/LICENSE-2.0.
# *
# * Unless required by applicable law or agreed to in writing, software
# * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# * License for the specific language governing permissions and limitations
# * under the License.
# *
# * SPDX-License-Identifier: Apache-2.0
# ********************************************************************************/

# -- The amount of replicas to run
replicaCount: 1

# -- Image of the main container
image:
  # -- Image repository
  repository: tractusx/managed-identity-wallet
  # -- PullPolicy
  pullPolicy: Always
  # -- Image tag (empty one will use "appVersion" value from chart definition)
  tag: "" 

nameOverride: ""
fullnameOverride: ""

# -- Parameters for the application (will be stored as secrets - so, for passwords, ...)
secrets: {}
#  DB_USER_NAME: xxx # Has to be the same as below in "postgresql" section
#  DB_PASSWORD: xxx # Has to be the same as below in "postgresql" section
#  KEYCLOAK_CLIENT_ID: xxx
#  ENCRYPTION_KEY: xxx  # 64 chars

# -- Parameters for the application (will be provided as plain environment variables)
envs:
  DB_HOST: "{{ .Release.Name }}-postgresql"
  DB_PORT: 5432
  # set it also in the init script in the postgres initdb section below!!
  DB_NAME: miw
  DB_USER_NAME: postgres
  DB_PASSWORD: postgres
  USE_SSL: false
  KEYCLOAK_REALM: miw_test
  KEYCLOAK_CLIENT_ID: miw_private_client
  AUTH_SERVER_URL: "http://{{ .Release.Name }}-keycloak"
  ENCRYPTION_KEY: 76a7834fb37e090c2789a9b1a76748d3
  APPLICATION_ENVIRONMENT: dev
  ENFORCE_HTTPS_IN_DID_RESOLUTION: false
#  DB_POOL_SIZE: xxx
#  KEYCLOAK_MIW_PUBLIC_CLIENT: xxx
#  MANAGEMENT_PORT: xxx
#  MIW_HOST_NAME: xxx
  MIW_HOST_NAME: "{{ .Release.Name }}-managed-identity-wallet:8080"
  AUTHORITY_WALLET_BPN: BPNL000000000000
#  AUTHORITY_WALLET_NAME: xxx
  AUTHORITY_WALLET_DID: did:web:{{ .Release.Name }}-managed-identity-wallet%3A8080:BPNL000000000000
#  VC_SCHEMA_LINK: xxx
#  VC_EXPIRY_DATE: xxx
#  KEYCLOAK_REALM: xxx
#  AUTH_SERVER_URL: xxx

# -- ServiceAccount configuration
serviceAccount:
  create: true
  annotations: {}
  name: ""

# -- Service configuration
service:
  type: ClusterIP
  port: 8080

# -- Ingress configuration
ingress:
  enabled: false
  annotations: {}
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

# -- PodSecurityContext
podSecurityContext: {}

# -- Preconfigured SecurityContext
securityContext:
  privileged: false
  allowPrivilegeEscalation: false
  runAsNonRoot: true
  runAsGroup: 11111
  runAsUser: 11111

# -- Resource boundaries
resources:
  requests:
    cpu: 250m
    memory: 500Mi
  limits:
    cpu: 2
    memory: 1Gi

# -- NodeSelector configuration
nodeSelector:
  "kubernetes.io/os": linux

# -- Tolerations configuration
tolerations: []

# -- Affinity configuration
affinity: {}

# -- PodAnnotation configuration
podAnnotations: {}

# -- Simple Postgresql backup solution (Dump data to second PV)
backup:
  # -- Backup database
  database:
    # -- Enable / Disable the backup
    enabled: false
    # -- Backup schedule (help: https://crontab.guru)
    cron: "* */6 * * *"
    # -- Storage configuration
    storage:
      # -- Set to true, if the PV should stay even when the chart release is uninstalled
      keepStorage: true
      # -- Disk size for backup content
      diskSize: 10G
      # -- storageClassName
      storageClassName: "-"

keycloak:
  enabled: true
  postgresql:
    enabled: false
  externalDatabase:
    host: '{{ .Release.Name }}-postgresql'
    port: 5432
    user: postgres
    password: postgres
    database: keycloak
  auth:
    adminUser: user
    adminPassword: password
    postgresql:
      enabled: false
  keycloakConfigCli:
    enabled: true
    existingConfigmap: keycloak-realm-config
  extraEnvVars:
    - name: KEYCLOAK_HOSTNAME
      value: "{{ .Release.Name }}-keycloak"

postgresql:
  primary:
    initdb:
      scripts:
        init_db_script.sh: |
          #!/bin/sh
          createdb -O postgres miw
      user: postgres
      password: postgres
  auth:
    password: postgres
    username: postgres
    postgresPassword: postgres
