image:
  name: "catenax-ng/product-core-managed-identity-wallets_service"
allowEmptyPassword: "\"yes\""
db:
  jdbcDriver: "org.postgresql.Driver"
auth:
  jwksUrl: "https://catenaxdev003akssrv.germanywestcentral.cloudapp.azure.com/iamcentralidp/auth/realms/CX-Central/protocol/openid-connect/certs"
  issuerUrl: "https://catenaxdev003akssrv.germanywestcentral.cloudapp.azure.com/iamcentralidp/auth/realms/CX-Central"
  redirectUrl: "https://custodian-dev.germanywestcentral.cloudapp.azure.com/callback"
  realm: "CX-Central"
  role: "access"
datapoolUrl: "https://catenax-bpdm-dev.germanywestcentral.cloudapp.azure.com"
logging:
  exposed: "INFO"
wallet:
  catenaXBpn: "BPNL000000000000"
acapy:
  imageName: "catenax-ng/product-core-managed-identity-wallets_acapy"
  tag: "0.7.3-5077299"
  ledgerUrl: "https://idu.cloudcompass.ca"
  label: "CatenaXIssuer"
  logLevel: "DEBUG"
  endpointPort: "8000"
  endpointUrl: "https://custodian-dev.germanywestcentral.cloudapp.azure.com:8000/"
  adminPort: "11000"
  adminUrl: "http://localhost:11000"
  networkIdentifier: "idunion:test"
  databaseHost: "10.244.2.207" # the IP of the postgres DB
postgresql:
  enabled: true
  auth:
    username: postgres
    password: ""
