apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: managed-identity-wallets
spec:
  destination:
    namespace: managed-identity-wallets
    server: 'https://kubernetes.default.svc'
  source:
    path: helm/managed-identity-wallets
    repoURL: 'https://github.com/catenax-ng/product-core-managed-identity-wallets.git'
    targetRevision: HEAD
    plugin:
      name: argocd-vault-plugin-helm
      env:
        - name: AVP_SECRET
          value: vault-secret
        - name: helm_args
          value: '-f ./managed-identity-wallets/values.yaml -f ./managed-identity-wallets/values-dev.yaml'
  project: project-portal