version: '3'

services:
  cx_postgres:
    image: postgres:14.2
    container_name: cx_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: cx_password
      PGDATA: /data/postgres-data
    volumes:
      - postgres-data:/data/postgres-data
    ports:
      - "5432:5432"

  cx_keycloak:
    image: jboss/keycloak:16.1.1
    container_name: cx_keycloak
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: catena
      KEYCLOAK_IMPORT: /tmp/catenax-realm.json
    volumes:
      - ./keycloak/catenax-realm.json:/tmp/catenax-realm.json
    ports:
      - "8081:8080"

  cx_acapy:
    image: acapy:latest
    ports:
      - "${ACAPY_ADMIN_PORT}:${ACAPY_ADMIN_PORT}"
      - "${ACAPY_ENDPOINT_PORT}:${ACAPY_ENDPOINT_PORT}"
    environment:
      WAIT_HOSTS: "db:5432"
      WAIT_HOSTS_TIMEOUT: "300"
      WAIT_SLEEP_INTERVAL: "5"
      WAIT_HOST_CONNECT_TIMEOUT: "3"
    entrypoint: /bin/bash
    command: [
       "-c",
       "aca-py start \
        -e ${ACAPY_ENDPOINT_URL} \
        --auto-provision \
        --inbound-transport http '0.0.0.0' ${ACAPY_ENDPOINT_PORT} \
        --outbound-transport http \
        --admin '0.0.0.0' ${ACAPY_ADMIN_PORT} \
        --wallet-type ${WALLET_TYPE} \
        --wallet-name ${WALLET_NAME} \
        --wallet-key ${WALLET_KEY} \
        --seed ${AGENT_WALLET_SEED} \
        --genesis-url ${LEDGER_URL}/genesis \
        --label ${LABEL} \
        --admin-insecure-mode \
        --auto-ping-connection \
        --jwt-secret ${JWT_SECRET} \
        --multitenant \
        --multitenant-admin \
        --log-level ${LOG_LEVEL}",
    ]

volumes:
  postgres-data:
