name: Build and push the latest build to staging

on:
  push:
    branches: [ main ]
  workflow_dispatch:
    branches: [ main ]

env:
  CX_CUSTODIAN_VERSION: "0.0.4"
  NAMESPACE: "custodian"
  SECRET: "custodian-staging-secret"
  SHORT_SHA: "default"
  LOAD_BALANCER_IP: "20.113.25.108"

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      # Checks out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Set outputs
        id: vars
        run: |
          echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
          echo "SHORT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Show version
        run: echo ${CX_CUSTODIAN_VERSION}.${SHORT_SHA}

      - name: Docker Login
        uses: docker/login-action@v1
        with:
          registry: ${{ secrets.CX_ACR_SERVER }}
          username: ${{ secrets.CX_ACR_USER }}
          password: ${{ secrets.CX_ACR_PASSWORD }}
      
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
            java-version: 17

      - name: Build with Gradle
        uses: gradle/gradle-build-action@4137be6a8bf7d7133955359dbd952c0ca73b1021
        with:
          arguments: build

      - name: Create dist
        uses: gradle/gradle-build-action@4137be6a8bf7d7133955359dbd952c0ca73b1021
        with:
          arguments: installDist

      - name: setup nodejs
        uses: actions/setup-node@master

      - name: build admin ui
        run: cd ui-src && npm install && npm run build && cp -r dist/* ../static

      - name: Build and push staging images
        uses: docker/build-push-action@v2
        with:
          context: .
          tags: ${{ secrets.CX_ACR_SERVER }}/catena-x/custodian:${{ env.CX_CUSTODIAN_VERSION }}.${{ env.SHORT_SHA }}
          push: true

  deploy:
    needs: build
    runs-on: ubuntu-20.04
    if: ${{ false }}  # disable for now

    steps:
      - uses: actions/checkout@v2

      - name: Install Helm
        uses: Azure/setup-helm@v1
        with:
          version: v3.3.1

      - name: Set the target Azure Kubernetes Service (AKS) cluster. 
        uses: azure/aks-set-context@v1
        with:
          creds: '${{ secrets.AZURE_SP_DEV013_TSI }}'
          cluster-name: ${{ env.CLUSTER_NAME }}
          resource-group: ${{ env.CLUSTER_RESOURCE_GROUP }}
      
      - name: Create namespace if doesn't exist
        run: |
          kubectl create namespace ${{ env.NAMESPACE }} --dry-run=client -o json | kubectl apply -f -

      - name: Create image pull secret for ACR
        uses: azure/k8s-create-secret@v1
        with:
          container-registry-url: ${{ secrets.CX_ACR_SERVER }}
          container-registry-username: ${{ secrets.CX_ACR_USER }}
          container-registry-password: ${{ secrets.CX_ACR_PASSWORD }}
          secret-name: ${{ env.SECRET }}
          namespace: ${{ env.NAMESPACE }}
          arguments: --force true

      - name: Run Helm Deploy app to dev
        run: |
          helm upgrade \
            --install \
            --atomic \
            --wait \
            --namespace ${{ env.NAMESPACE }} \
            --generate-name \
            ./helm/custodian \
            --set image.registry=${{ secrets.CX_ACR_SERVER }} \
            --set image.name=catena-x/custodian \
            --set image.tag=${{env.CX_CUSTODIAN_VERSION}}.${{env.SHORT_SHA}\
            --set imageCredentials.registry=${{ secrets.CX_ACR_SERVER }}\
            --set imageCredentials.username=${{ secrets.CX_ACR_USER }}\
            --set imageCredentials.password=${{ secrets.CX_ACR_PASSWORD }}\
            --set loadBalancerIP=${{env.LOAD_BALANCER_IP}}
